version: '3'

services:
  api-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./profiles:/app/profiles
    environment:
      - WATI_API_KEY=${WATI_API_KEY}
      - BOT_API_URL=${BOT_API_URL}
      - PROFILES_DIR=profiles
    restart: unless-stopped
    command: python api_server.py

  wati-integration:
    build: .
    depends_on:
      - api-server
    volumes:
      - ./profiles:/app/profiles
    environment:
      - WATI_API_KEY=${WATI_API_KEY}
      - BOT_API_URL=${BOT_API_URL:-http://api-server:8000}
      - PROFILES_DIR=profiles
    restart: unless-stopped
    command: python wati_integration.py
